import Navbar from "./components/navBar";
import "./globals.css";
import StoreProvider from "./storeProvider";
import ThemeProviderr from "./themeProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <ThemeProviderr>
            <Navbar />
            {children}
          </ThemeProviderr>
        </StoreProvider>
      </body>
    </html>
  );
}
